name: Deploy Next.js site to Pages

on:
  push:
    branches:
      - main  # Ensure proper indentation and syntax

jobs:
  # Build job
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Build
        id: docker_build
        run: |
          echo "Building Docker image..."
          docker build -t nextjs-app .

      - name: Run Docker container (optional, depending on your app)
        id: docker_run
        run: |
          echo "Running Docker container..."
          docker run -p 3000:3000 nextjs-app
